# Generated by Django 4.1.3 on 2022-11-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='down_vote',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='up_vote',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
