# Generated by Django 4.1.3 on 2022-11-25 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_vote_down_vote_alter_vote_up_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voted_by',
        ),
    ]
