# Generated by Django 4.1.3 on 2022-11-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_article_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
    ]
