# Generated by Django 4.1.3 on 2022-11-28 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0015_roadmap_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='Roadmap',
        ),
        migrations.CreateModel(
            name='Roadmapsubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.roadmap')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='link',
            name='sub_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.roadmapsubtitle'),
        ),
    ]
